### ISSUE TITLE
Most recent update is using a version of Google Play Services that my phone does not support

### ISSUE THREAD

**Issue by bramp** [irccloud/android#109]
With the most recent irccloud app update, I get a prompt that I must update Google Play services. However, on the Google Play store when I view Google Play services it says "Your device isn't compatible with this version".

My device, a Nexus 6 has Google Play services 6.7.74, running on Android 5.1.

**Comment by c99koder** [comment]
The latest version of Google Play Services is 7.0 and was pushed out to devices a month ago, not sure why it's not available for your device in the Play Store, you'd have to ask Google.

**Comment by bramp** [comment]
Do you have any reporting that may indicate if other users are also on a older Play Services? Presumably the latest version of irccloud is using features only available in 7.0?
