### ISSUE TITLE
Nickname on separate line forces timestamps to right side

### ISSUE THREAD

**Issue by ThiconZ** [irccloud/android#136]
In the Android 3.0(61) and Android 3.1(62) builds when the option `Nicknames on a separate line` is enabled, timestamps will be forced to the right side of the screen. Toggling the `Right hand side timestamps` setting does not fix this issue either. The only way to get timestamps back to the left side appear to be disabling the `Nicknames on a separate line` options.

**Comment by c99koder** [comment]
This is intentional, and matches the behavior of the web client.  You can have timestamps on the left with nicknames on a separate line only if you turn off user icons.

**Comment by c99koder** [comment]
Looks like the setting isn't working quite right even with user icons turned off. It will be fixed in the next update, thanks for letting us know about the issue.

**Comment by c99koder** [comment]
A fix for this issue will be available in the beta channel shortly. You can opt in for beta updates here: https://play.google.com/apps/testing/com.irccloud.android
