### ISSUE TITLE
Facing troubles importing the project to Android Studio.

### ISSUE THREAD

**Issue by yashkant** [irccloud/android#150]
The documentation is not clear and sufficient to build the project on Android Studio after cloning. By default the project is detected as an Android Studio project (but the directory structure seems like that of Eclipse) and migrating to Android Studio cannot be initialized. Please provide help

**Comment by c99koder** [comment]
This is an Android Studio project. Don't convert it from Eclipse, just open the build.gradle file in Android Studio as the instructions stated.  Make sure you've also checked out the android-websockets project into the parent direct.
