### ISSUE TITLE
Setting topic that begins with a nick breaks "nick set the topic: [...]" on Android

### ISSUE THREAD

**Issue by carstenhag** [irccloud/android#167]
Compare the web version and the android version:

![web](https://i.imgur.com/SbqEznd.png)
![android](https://i.imgur.com/iVbQtQ3.jpg)

Topics with which the bug appears:
```
<shpank> "gibt keine news" | Moters Gewicht: 72.2kg
shpank> "gibt keine news" | Moters Gewicht: 72.2kg

```

Topics with which the bug does not appear:

```
blub> "gibt keine news" | Moters Gewicht: 72.2kg
"gibt keine news" | Moters Gewicht: 72.2kg
```

`shpank` is a user in the channel. `blub` is not.  
My guess is, that it detects a nick and then styles it in some way, and the topic shows up in a weird way like that.

**Comment by c99koder** [comment]
Make sure you've downloaded the latest version of the app (4.9.2) from the Play Store, as this issue should have already been fixed.

**Comment by carstenhag** [comment]
Play Store says I have 4.9.2, bug appears. There's no update available.

**Comment by carstenhag** [comment]
Sam Steele <notifications@github.com> schrieb am Fr., 8. Juni 2018, 15:10:
