### ISSUE TITLE
Feature Request: notification with ISON on nicknames

### ISSUE THREAD

**Issue by Rapiere** [irccloud/android#171]
IRCCloud would be perfect if it could sends notification on some specific nicknames (configurable on private message tab), by using ISON server feature: https://tools.ietf.org/html/rfc1459#section-5.8
It would probably increase a bit bandwidth need and could be saved for paid accounts, or have a limit on time frequency (like every minute on paid account, 10-15 minutes on free accounts).

**Comment by c99koder** [comment]
We don't currently have plans to support polling for status using ISON, it doesn't scale well with the large number of users on our service.  However, some IRC servers support a `/monitor` or `/watch` command that will let the IRC server notify you when someone goes online or offline.  The monitor command is part of the IRCv3 spec, so more servers will support it as they update their IRCd software in the future.  Here's the docs for the IRCv3 monitor command: https://ircv3.net/specs/core/monitor-3.2.html
