### ISSUE TITLE
NickServ password option uses "/ns" but this is not supported in all servers

### ISSUE THREAD

**Issue by jotenko** [irccloud/android#174]
Under each server's Advanced Options, you might write down your NickServ password.

The problem with this, is that IRCcloud will issue the command "/ns identify" underneath. The problem lies in the fact that not all servers support the clause "/ns", however, virtually all support "/msg nickserv <nickname> <password>". QuakeNet is a good example of this.

A workaround in these servers is to write the down the "/msg nickserv identify" command under Commands to run on connect, but as you can understand, is not a good security option to have your password in clear text in an IRC client...

I suggest that IRCcloud starts using "/msg nickserv identify" instead of "/ns identify" for authentication of users.

Thanks.

**Comment by jwheare** [comment]
This is not a question specific to the android app, but the rationale for not using /msg nickserv identify is that this will persistently log your password on every connection attempt in a conversation with nickserv, whereas using /ns or /nickserv will not.

Bear in mind that the commands the run on connect are encrypted in the database, and are only visible while you're looking at the advanced options for a server.
