### ISSUE TITLE
Copy - paste join/part/quit messages have some weird format issues

### ISSUE THREAD

**Issue by TheMythPT** [irccloud/android#176]
Recently I've seen a user being banned/disconnected due to spam, as can be seen in the attachment below:

![Screenshot_20191020_122227](https://user-images.githubusercontent.com/25697531/67158150-af83a500-f334-11e9-8f77-b649b508d746.jpg)

When trying to copy and paste the quit message from within IRCCloud app, this the pasting result:

`11:13:49 88b2dc⇐ E7AA00~ 88b2dcPeGaSuS quit (CloudBNC@SimosNap-6g8mgi.cloudbnc.tk) Filtered:  Your message contain some special chars usually used for spam purpose.`

Seems the app has some issues with the formatting in the join/part/quit messages.

**Comment by c99koder** [comment]
fixed in 1c8516646e6f56eae3180d7a966476d8f0646775
