### ISSUE TITLE
Invalid Hostname

### ISSUE THREAD

**Issue by shivam-kapila** [irccloud/android#180]
My IRCCloud app is unable to connect to chat.freenode.net:6697. Please look into this
![Screenshot_20200206-185635](https://user-images.githubusercontent.com/33172244/73940978-6c186b00-4912-11ea-9cbd-8e8f825bf739.png)

**Comment by c99koder** [comment]
Please use our IRC channel #feedback on irc.irccloud.com or contact us via email at team@irccloud.com for customer service requests.
