### ISSUE TITLE
Do you support F-Droid inclusion?

### ISSUE THREAD

**Issue by egils-consulting** [irccloud/android#183]

**Comment by c99koder** [comment]
The app requires Google Play Services for various features such as push notifications, so we don't have any plans to distribute the app outside of the Play Store.

**Comment by egils-consulting** [comment]
This is not necessarily a blocker because you could implement MicroG services for the fdroid built while still using firebase in the android app if I understand correctly.

**Comment by c99koder** [comment]
MicroG is something you install on your own device at your own risk, not something we can provide support for. We have no plans to support the app being distributed outside of the Play Store.
