### ISSUE TITLE
ER: Notification Sync

### ISSUE THREAD

**Issue by nahun** [irccloud/android#78]
It would be awesome if notifications in IRCCloud synced across devices and even the web app. So if I dismiss a notification on my phone, it will clear on my tablet and on the web app too.

I believe this is done with Google Cloud Messaging? http://developer.android.com/google/gcm/

Just an idea, I don't know if its feasible to implement.

Thanks!

**Comment by cyril-bouthors** [comment]
Hi,

Thanks for IRCCloud, it's a great service, I'm a very happy customer.

I'm also hit by this issue so I thought I could help this been improved.

As far as I know, the other apps like Gmail and Facebook manage to handle cross-devices notifications correctly with a simple trick: when a notification is read somewhere else, the whole channel is marked as read and the remaining notifications pushed again.

It's currently the only way to do it under Android if I remember correctly.

Would it be possible to do that? It's getting hard to receive tons of useless Android notifications when I use the webapp 10 hours a day…

Thanks!

**Comment by azamatms** [comment]
The Server side could check if the user is marked as away or not.

If the user is away then fire away with the android notification, if not don't notify the phone since the client is already being used elsewhere.
