### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by creesch** [irccloud/android#93]
I was wondering if there are any plans to create a dark theme for the client. On the website variant it is possible to use custom stylesheets which on androids is obviously not a thing. 
I often use the android client late during the day or just before going to sleep, where the light blue theme (As nice as it is) is rather bright and blinding.

**Comment by echoe** [comment]
i'd like this as well. it affects battery life [theoretically] a bunch with AMOLED, too.

**Comment by Patrik356b** [comment]
Add to webclient too

**Comment by creesch** [comment]
@Patrik356b considering that you can easily do a custom stylesheet with an extension like stylish that is effectively already possible.

**Comment by Patrik356b** [comment]
Does not apply to all browsers

**Comment by c99koder** [comment]
Dark themes are now available on the web, and will be included in the next app update

**Comment by creesch** [comment]
Awesome!
